services:
  - type: web
    name: license-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SUPABASE_URL
        value: https://tyhcdhwxupgkaoekzgin.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5aGNkaHd4dXBna2FvZWt6Z2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDA3NzQsImV4cCI6MjA2MzA3Njc3NH0.PfhEsUalf3oMPJ2Z-4iaFtSJgMC9c62Yh2N5X8Gv1IM